[package]
name = "hose-devnet-macros"
description = "Macro crate for devnet tests with Hose"
edition = "2024"

[lib]
proc-macro = true
crate-type = ["proc-macro"]
source = "src/lib.rs"

[dependencies]
quote = "1.0.3"
syn = { version = "^2", features = ["full"] }
proc-macro2 = "1.0.78"
